### ISSUE TITLE
Add support for scoped packages

### ISSUE THREAD

**Issue by bfred-it** [juliangruber/ghub.io#24]
Example: 

https://www.npmjs.com/package/@shinnn/eslint-config-node ✅
https://github.com/shinnn/eslint-config-node ✅
http://ghub.io/@shinnn/eslint-config-node ❌

**Comment by zeke** [comment]
The [skimdb endpoint](https://github.com/juliangruber/ghub.io/blob/master/index.js#L15) doesn't serve up scoped packages. There's a new endpoint for that: replicate.npmjs.com

https://github.com/nice-registry/package-stream is what I use to consume it:

```js
const registry = require('package-stream')()

registry
  .on('package', function (pkg) {
    // nice clean package object
  })
  .on('up-to-date', function () {
    // consumed all changes (for now)
    // The stream will remain open and continue receiving package
    // updates from the registry as they occur in real time.
  })
```

**Comment by juliangruber** [comment]
that module looks sweet! we should use this instead, together with the leveldb package cache

**Comment by fregante** [comment]
Seems to work now!

http://ghub.io/@shinnn/eslint-config-node ✅

**Comment by zeke** [comment]
Yo @bfred-it just FYI the new canonical repo is https://github.com/nice-registry/ghub.io

**Comment by fregante** [comment]
Best to move/archive this one then

**Comment by zeke** [comment]
> archive this one

good call
