### ISSUE TITLE
make a friendlier default bin for use with npx

### ISSUE THREAD

**Issue by js-n** [juliangruber/ghub.io#26]
I love using ghub.io from my browser address bar - thank you for writing/maintaining it!
now, [npx](https://github.com/zkat/npx) has become a big part of my workflow from my other terminal interface, my shell.

I'd like to be able to `npx ghub cowsay` and have it output the url, `https://github.com/piuccio/cowsay`, maybe with [opener](https://www.npmjs.com/package/opener) by default (and a flag to get plain output).

What do you think? I'm happy to take a stab at implementing it if you're open to the idea.

**Comment by juliangruber** [comment]
you mean something like `npx $(ghub cowsay)` would run `npx https://github.com/piuccio/cowsay`?

**Comment by juliangruber** [comment]
Try `npx $(npm show cowsay repository.url)`, that should already work and you can turn it into a shell function like

```bash
nnpx () {
  npx $(npm show $1 repository.url)
}
```

**Comment by js-n** [comment]
that's not exactly what I had in mind, but thanks for reminding me about `npm show`/`npm view`, that makes a bunch of sense to use as the source for this information. I took a stab at implementing this in a separate package, `ghub-cli` - the readme there should give you a sense of the usage https://github.com/js-n/ghub-cli

I'll close this issue for now. If you have any interest in pulling ghub-cli into this package for the sake of the namespace, I'd be happy to merge them, and if not, I completely understand. Cheers.
